{
 "title": "Amarisoft 5G Infra Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "epc_ip",
    "query": "query_result(sum by (exported_instance)(collectd_resources_vcpu {resources=\"mme\"}))"
   },
   {
    "name": "enb_id",
    "query": "query_result(sum by (s1_connections)(collectd_s1_connections_count {exported_instance=\"$epc_ip\"}))"
   },
   {
    "name": "gnb_id",
    "query": "query_result(sum by (ng_connections)(collectd_ng_connections_count {exported_instance=\"$epc_ip\"}))"
   },
   {
    "name": "mme_ue_id",
    "query": "query_result(sum by (ue_stats)(collectd_ue_stats_bitrate{exported_instance=\"$enb_ip\"}))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1 style=\"background-color:#339933 ; text-align:center\">MME </h1>"
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "collectd_resources_vcpu{exported_instance=\"$epc_ip\",resources=\"mme\"} "
    }
   ]
  },
  {
   "title": "# s1 connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(collectd_s1_connections_count{exported_instance='$epc_ip',job=\"5g_amarisoft_collectd\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "s1 connections Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "collectd_s1_connections_count{exported_instance=\"10.30.0.223\"}"
    }
   ]
  },
  {
   "title": "ng connections Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "collectd_ng_connections_count{exported_instance=\"10.30.0.223\"}"
    }
   ]
  },
  {
   "title": "# ng connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(collectd_ng_connections_count{exported_instance='$epc_ip',job=\"5g_amarisoft_collectd\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "UE infos",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(collectd_ue_info_enb_ue_id {exported_instance='$enb_id'}) by (exported_instance, ue)"
    },
    {
     "expr": "sum(collectd_ue_info_mme_ue_id {exported_instance='$enb_id'}) by (exported_instance, ue)"
    },
    {
     "expr": "sum(collectd_ue_info_registered {exported_instance='$enb_id'}) by (exported_instance, ue)"
    },
    {
     "expr": "sum(collectd_ue_info_total_dl {exported_instance='$enb_id'}) by (exported_instance, ue)"
    },
    {
     "expr": "sum(collectd_ue_info_total_ul {exported_instance='$enb_id'}) by (exported_instance, ue)"
    }
   ]
  },
  {
   "title": "Total UEs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(collectd_s1_connections_count{exported_instance=\"$epc_ip\"} OR on() vector(0) + collectd_ng_connections_count{exported_instance=\"$epc_ip\"} OR on() vector(0))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "content": "<h1 style=\"background-color:#339933 ; text-align:center\">ENB/GNB </h1>"
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "collectd_resources_vcpu{exported_instance=\"$enb_id\",resources=\"enb\"} OR on() collectd_resources_vcpu{exported_instance=\"$gnb_id\",resources=\"enb\"} "
    }
   ]
  },
  {
   "title": "ENB Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 5, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "collectd_cell_throughput_dl{exported_instance='$enb_id',type=\"lte\"}/1000000",
     "legendFormat": "{{exported_instance}} - {{type}}"
    },
    {
     "expr": "collectd_cell_throughput_ul{exported_instance='$enb_id',type=\"lte\"}/1000000",
     "legendFormat": "{{exported_instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "ENB UE_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "#users" }
   ],
   "targets": [
    {
     "expr": "collectd_enb_ue_count{exported_instance='$enb_ip'}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "UE Statistics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "content": "# title" },
  {
   "title": "ENB UE Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Mbps" }
   ],
   "targets": [
    {
     "expr": "collectd_ue_stats_bitrate{exported_instance='$enb_ip',type=\"dl\"}/1000000",
     "legendFormat": "ENB: {{exported_instance}} - MME_id: {{ue_stats}} - {{type}}_throughput"
    },
    {
     "expr": "-collectd_ue_stats_bitrate{exported_instance='$enb_ip',type=\"ul\"}/1000000",
     "legendFormat": "ENB: {{exported_instance}} - MME_id: {{ue_stats}} - {{type}}_throughput"
    }
   ]
  },
  {
   "title": "UE dl_mcs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "MCS" }
   ],
   "targets": [
    {
     "expr": "collectd_ue_stats_mcs{exported_instance='$enb_ip',type=\"dl\"}",
     "legendFormat": "ENB: {{exported_instance}} - MME_id: {{ue_stats}} - {{type}}_mcs"
    }
   ]
  },
  {
   "title": "UE ul_mcs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "MCS" }
   ],
   "targets": [
    {
     "expr": "collectd_ue_stats_mcs{exported_instance='$enb_ip',type=\"ul\"}",
     "legendFormat": "ENB: {{exported_instance}} - MME_id: {{ue_stats}} - {{type}}_mcs"
    }
   ]
  },
  {
   "title": "ENB UE pucch_snr",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "dB" }
   ],
   "targets": [
    {
     "expr": "collectd_ue_stats_pucch_snr{exported_instance='$enb_ip'}",
     "legendFormat": "ENB: {{exported_instance}} - MME_id: {{ue_stats}} "
    }
   ]
  },
  {
   "title": "ENB UE pusch_snr",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "dB" }
   ],
   "targets": [
    {
     "expr": "collectd_ue_stats_pusch_snr{exported_instance='$enb_ip'}",
     "legendFormat": "ENB: {{exported_instance}} - MME_id: {{ue_stats}} "
    }
   ]
  },
  {
   "title": "ENB UE cqi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "CQI" }
   ],
   "targets": [
    {
     "expr": "collectd_ue_stats_cqi{exported_instance='$enb_ip'}",
     "legendFormat": "ENB: {{exported_instance}} - MME_id: {{ue_throughput}} - {{type}}"
    }
   ]
  }
 ]
}